config/routes.rb
Rails.application.routes.draw do 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'static_pages#home'
  get 'static_pages/mysterious_page'

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  attr_accessor :remember_token
  
  #2 fonctions utilisées par la méthode remember
  class << self
    #Create a digest based on a string
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end



  def remember
    #Créer un remember_token
    self.remember_token = User.new_token
    #Met le digest de ce token dans la base de donnée
    update_attribute( :remember_digest, User.digest(@remember_token) )  
  end

  def forget
     update_attribute( :remember_digest, nil )  
  end

  #Method to identify wether the user is the right one (the digest of the input remember_token == remember_digest)
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to current_user
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:mysterious_page]

  def home
  end

  def mysterious_page
  end

  private

  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

 def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Sign up successful"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    else
      @current_user = nil
    end
  end

  def remember(user)
    #use the User method remember
    user.remember
    #create the 2 cookies one for id and one with the remember_token
    cookies.permanent[:remember_token] = user.remember_token
    cookies.permanent.signed[:id] = user.id
  end

  def forget(user)
    #use the User method forget
    user.forget
    #delete the 2 cookies
    cookies.delete(:id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <p><%= link_to "Home", root_path %></p>
  <% if logged_in? %>
    <p><%= link_to "Log Out", logout_path, method: :delete %></p>
  <% else %>
    <p><%= link_to "Log In", '/login' %></p>
  <% end %>      
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpMembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-0.8.1.min.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert_message"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome!</h1>

<% if logged_in? %>
  <p>Congratulations, you can have the answer to Life, the Universe and Everything, by clicking on the following button!</p>
  <%= button_to "Oh yeah!", static_pages_mysterious_page_path, method: 'get' %>
<% else %>
  <p>If you want to have the answer to Life, the Universe and Everything, please log in!</p>
  <%= button_to "Log In", login_path, method: 'get' %>

<% end %>

app/views/static_pages/mysterious_page.html.erb
<h1>The ultimate answer to Life, the Universe and Everything:</h1>
<h2>42</h2>

app/views/users/edit.html.erb
<h1>Edit your profile here</h1>


<%= form_for(@user) do |f| %>
      
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </p>

  <p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </p>

  <p>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit "Update info" %>
<% end %>

app/views/users/index.html.erb
<h1>List of recorded users</h1>

<p>
<% @users.each do |user| %>
  <ul>
    <li><%= user.name %>, <%= user.email %></li>
  </ul>
<% end %>
</p>

app/views/users/new.html.erb
<h1>Sign up form</h1>

<%= form_for(@user) do |f| %>
      
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </p>

  <p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </p>

  <p>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1>Profile page</h1>

<p>Name : <%= @user.name %></p>
<p>Email : <%= @user.email %></p>

<p><%= link_to "Edit your profile", edit_user_path %></p>
<p><%= link_to 'Delete your profile', @user, method: :delete %></p>